name: Node.js CI

on:
  push:
    branches: [ master, docker ]
  pull_request:
    branches: [ master, docker ]

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set var for getting tag or branch
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Login to GitLab
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.GITLAB_SERVER }}
          username: ${{ secrets.GITLAB_USER }}
          password: ${{ secrets.GITLAB_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@f3c886e26b64d7e5ef5ff5f574efc88b317b8451
        with:
          images: ${{ secrets.GITLAB_USER }}/${{ github.event.repository.name }}
          tags: type=sha,prefix={{branch}}-

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }
